### ISSUE TITLE
API is not clear to me about notational entry of options: upper: and lower: for root finding optimistix.Bisection/Newton

### ISSUE THREAD

**Issue by TomClarkMassSpec** [patrick-kidger/optimistix#18]
Hi Patrick,
```
solver = optx.Bisection(rtol=1e-19, atol=1e-15, lower = jnp.array(0.), upper = jnp.array(64000) )
y0 = (jnp.array(0.01))
sol = optx.root_find(fn=speed_curve_function, solver = solver, y0 = y0, args = root_find_pytree)
Thv = sol.value

```
I've tried inserting upper and lower several different ways. 

Thanks,
Tom

**Comment by patrick-kidger** [comment]
You want:
```python
optx.root_find(..., options=dict(lower=..., upper=...))
```
The `options` in the docstring is referring to the argment of the name in `root_find`. I can see that that's not the clearest for new users -- I'll tweak the docs to highlight the appropriate way to pass this in.

**Comment by patrick-kidger** [comment]
I've just opened #19 for this.

To explain why these are passed in a separate location, by the way -- this is to separate information about the solver itself (`Bisection(...)`) from the details of the problem it is being applied to (`fn=..., options=...`).

**Comment by TomClarkMassSpec** [comment]
Thank you. That part of it worked. Now to deal with inf.
