### ISSUE TITLE
Error when trying to serve documentation

### ISSUE THREAD

**Issue by johannahaffner** [patrick-kidger/optimistix#90]
Hi Patrick, 

I wanted to check if my docstrings look good in the documentation :) 
So I tried running `mkdocs serve` and I got the following error: 

```python
    raise AliasResolutionError(self) from error
_griffe.exceptions.AliasResolutionError: Could not resolve alias optimistix._misc.max_norm pointing at lineax.internal.max_norm (in optimistix/_misc.py:13)
```

I tried re-solving it a few ways - cloning the synced fork afresh, in a new venv, with fresh installations of mkdocs plugins and so on. 
I also tried importing lineax in the mkdocs.yml handler setup, but that did not help either. I'm not experienced with mkdocs, so I'd love a pointer :) 

This is optimistix 0.0.8 and lineax 0.0.7.

That said, it is not urgent.

**Comment by patrick-kidger** [comment]
This looks like you have the wrong versions of the doc-building stack installed. In particular I recognize `griffe` as being a mkdocstrings-associated library that came out after the versions of the doc libraries we are pinned to at the moment.

Have you ran `pip install -r docs/requirements.txt`?

**Comment by johannahaffner** [comment]
Thank you! I force-reinstalled and it appears that I package I already had caused conflicts.

Installing from `docs/requirements.txt` I'm now getting this error in both Python3.11 and 3.12: 

```python
  File "/Users/jhaffner/Desktop/trial/optimistix/.venv/lib/python3.11/site-packages/mkdocs_autorefs/plugin.py", line 77, in <module>
    class AutorefsPlugin(BasePlugin[AutorefsConfig]):
                         ~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: type 'BasePlugin' is not subscriptable
```

This is optimistix 0.0.8 with no changes of my own in a fresh virtual environment. (Error looks exactly the same for 3.12.). 
Pip freeze gives me:

mkdocs==1.3.0
mkdocs-autorefs==1.2.0
mkdocs-include-exclude-files==0.0.1
mkdocs-material==7.3.6
mkdocs-material-extensions==1.3.1
mkdocstrings==0.17.0
