### ISSUE TITLE
Problem with Adaptations of "Interactively step through a solve"

### ISSUE THREAD

**Issue by matillda123** [patrick-kidger/optimistix#96]
Hi,

I tried to adapt the example [Interactively step through a solve](https://docs.kidger.site/optimistix/examples/interactive/) to other solvers e.g. GradientDescent or BFGS. But I cannot get it to work. 
Is that because I am missing something about the implementation or does this only work for root finding?

Below i just copied the bisection example. 
I modified the function to have a minimum, switched the solver to GradientDescent and set the options to None.

```
import equinox as eqx
import jax
import jax.numpy as jnp
import optimistix as optx

@eqx.filter_jit
def fn(y, args):
    out = (y - jnp.tanh(y + 1))**2
    aux = None
    return out, aux

solver = optx.GradientDescent(rtol=1e-3, atol=1e-3, learning_rate=1)
y = jnp.array(10)
args = None
options = None
f_struct = jax.ShapeDtypeStruct((), jnp.float32)
aux_struct = None
tags = frozenset()

def solve(y, solver):
    step = eqx.filter_jit(
        eqx.Partial(solver.step, fn=fn, args=args, options=options, tags=tags)
    )
    terminate = eqx.filter_jit(
        eqx.Partial(solver.terminate, fn=fn, args=args, options=options, tags=tags)
    )

    state = solver.init(fn, y, args, options, f_struct, aux_struct, tags)
    done, result = terminate(y=y, state=state)

    while not done:
        print(f"Evaluating point {y} with value {fn(y, args)[0]}.")
        y, state, aux = step(y=y, state=state)
        done, result = terminate(y=y, state=state)
    if result != optx.RESULTS.successful:
        print(f"Oh no! Got error {result}.")
    y, _, _ = solver.postprocess(fn, y, aux, args, options, state, tags, result)
    print(f"Found solution {y} with value {fn(y, args)[0]}.")

solve(y, solver)
```

This results in 

> ValueError: linearized function called on tangent values inconsistent with the original primal values: got ShapedArray(int64[], weak_type=True) for primal aval ShapedArray(int64[], weak_type=True)

**Comment by matillda123** [comment]
Hey,

thanks for the answer. When I used `jnp.array(10.)` I got another error.

> TypeError: true_fun and false_fun output must have identical types, got
(('ShapedArray(float64[], weak_type=True)', EvalGrad(
  f='DIFFERENT ShapedArray(float64[], weak_type=True) vs. ShapedArray(float32[])',
  grad='ShapedArray(float64[], weak_type=True)'
), None, _SteepestDescentState(grad='ShapedArray(float64[], weak_type=True)'), 'ShapedArray(bool[])'), Static(
  _leaves=[],
  _treedef=PyTreeDef((None, CustomNode(EvalGrad[('f', 'grad'), (), ()], [None, None]), None, CustomNode(_SteepestDescentState[('grad',), (), ()], [None]), None))
)).

But this only happens when I call `jax.config.update("jax_enable_x64", True)`. The above error is then solved when correcting the type in f_struct to jnp.float64.

**Comment by johannahaffner** [comment]
Hi Matilda, 

yes, these types have to match.

Interactive solving means that you'll have to do some of the work optimistix will otherwise do for you in the background.

Glad it's working out, happy solving!
